name: ai_tutor
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_tts: ^3.7.0
  http: ^1.1.0
  logger: ^2.0.1
  sqflite: ^2.3.0
  path: ^1.8.3
  speech_to_text: ^6.3.0
  permission_handler: ^10.4.3
  flutter_translate: ^4.0.4
  flutter_dotenv: ^5.1.0
  modal_bottom_sheet: ^2.1.2
  video_player: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/seoul-logo.png
    - assets/images/person-circle.png
    - assets/images/Group.png
    - assets/images/Lim.png
    - assets/images/main1.png
    - assets/images/main2.png
    - assets/images/main3.png
    - assets/images/main4.png
    - assets/images/gold.png
    - assets/images/nft.png
    - assets/images/aiPic.png
    - assets/images/qr.png
    - assets/images/Stamp.png
    - assets/images/goToHero.png
    - assets/images/test_video.mp4
